"""add profile fields to student

Revision ID: 3de1c4fa45c5
Revises: 
Create Date: 2026-09-26 22:38:43.130270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3de1c4fa45c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_table('admins')
    op.add_column('students', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('students', sa.Column('university', sa.String(), nullable=True))
    op.add_column('students', sa.Column('degree', sa.String(), nullable=True))
    op.add_column('students', sa.Column('graduation_status', sa.String(), nullable=True))
    op.add_column('students', sa.Column('semester', sa.String(), nullable=True))
    op.add_column('students', sa.Column('graduation_year', sa.String(), nullable=True))
    op.add_column('students', sa.Column('graduation_date', sa.DateTime(), nullable=True))
    op.add_column('students', sa.Column('location', sa.String(), nullable=True))
    op.add_column('students', sa.Column('linkedin', sa.String(), nullable=True))
    op.add_column('students', sa.Column('github', sa.String(), nullable=True))
    op.add_column('students', sa.Column('portfolio', sa.String(), nullable=True))
    op.add_column('students', sa.Column('resume_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'resume_text')
    op.drop_column('students', 'portfolio')
    op.drop_column('students', 'github')
    op.drop_column('students', 'linkedin')
    op.drop_column('students', 'location')
    op.drop_column('students', 'graduation_date')
    op.drop_column('students', 'graduation_year')
    op.drop_column('students', 'semester')
    op.drop_column('students', 'graduation_status')
    op.drop_column('students', 'degree')
    op.drop_column('students', 'university')
    op.drop_column('students', 'phone')
    op.create_table('admins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('admins_pkey')),
    sa.UniqueConstraint('username', name=op.f('admins_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    # ### end Alembic commands ###
