"""add company registration fields

Revision ID: 780192b95b40
Revises: 3de1c4fa45c5
Create Date: 2026-09-28 04:30:56.047126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '780192b95b40'
down_revision: Union[str, Sequence[str], None] = '3de1c4fa45c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('contact_person', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('location', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('website', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('description', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('trade_license_path', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('license_issue_date', sa.Date(), nullable=True))
    op.add_column('companies', sa.Column('license_expiry_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'license_expiry_date')
    op.drop_column('companies', 'license_issue_date')
    op.drop_column('companies', 'trade_license_path')
    op.drop_column('companies', 'description')
    op.drop_column('companies', 'website')
    op.drop_column('companies', 'location')
    op.drop_column('companies', 'phone')
    op.drop_column('companies', 'contact_person')
    op.drop_column('companies', 'industry')
    # ### end Alembic commands ###
